version: '3.8'
services:
  mia:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1988:1988"
    env_file:
      - .env
    volumes:
      - ./data:/data
    # equivalent of --gpus all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]